### ISSUE TITLE
KubeJS error with forge on 1.16.5

### ISSUE THREAD

**Issue by Adirelle** [xMGZx/UnifyTags#10]
I've got this error at loading:

Error :
```
[08:52:48] [ERR  ] Error occurred while handling event 'tags.items': TypeError: Cannot find function getObjectIds in object items:forge:ores/copper. (server_scripts:unify.js#205)
```

It seems that getObjectIds does not exist in the TagWrapper class: https://mods.latvian.dev/books/kubejs/page/tageventjs

---
Minecraft version: 1.16.5
Forge : v36.2.34 
KubeJS: 1605.3.19-build.299
UnifyTags: 5ceb46aa5b13aaf44b974fdbfd7b7f477b5750f5

**Comment by jimmon89** [comment]
i can confirm, i have it on my private server/pack as seen in this [log](https://pastebin.com/y7TGVWKu)

**Comment by mathgeniuszach** [comment]
The official wiki is very outdated and is missing a large number of functions in it. Here's your function right here:
https://github.com/KubeJS-Mods/KubeJS/blob/08a786a8cb6bd70e7f9e8d6ae30009821a45a6c5/common/src/main/java/dev/latvian/mods/kubejs/server/TagEventJS.java#L196=

It seems like they renamed it from getAllItemIds to getObjectIds and that's where this problem lies. I'll attempt to call whichever function is available.
