### ISSUE TITLE
Not unifying Lead, nickel and silver properly.

### ISSUE THREAD

**Issue by arcanecannon** [xMGZx/UnifyTags#17]
For some reason the script refuses allow the conversion of ore blocks(When silk touched) into dust. The normal stone variants only allow to be directly smelted into ingots. The deep slate variants are unaffected and have unified properly. Raw ore bits(When mined without silk touch) also remains functional.

I have not touched or configured the scripts save allowing all unified items to remain unhidden. The following image is verbatium as displayed for Silver, and nickel as well.
![image_2022-08-08_150816222](https://user-images.githubusercontent.com/83865549/183495051-6f3209af-7bf4-4c76-8e8f-86e8e5212d3d.png)

Mods Unified,
Thermal Expansion
Immersive Engineering
Create

**Comment by mathgeniuszach** [comment]
I don't understand what you're expecting the script to do by default. In what world is an ore block supposed to drop dust when you mine it with silk touch by DEFAULT?!?!? It's meant to be configured if it's not unifying things the way you want.

**Comment by mathgeniuszach** [comment]
If you're talking about how, after mining a block through silk touch, you cannot put it into a modded machine to turn it into dust, this is likely because the mod does not register it's recipes to be modifiable through kubejs's `.replaceInput()` and `.replaceOutput()` recipes. There is no plan at the moment to unify recipes that do not register themselves through this method, however, a potential workaround has been mentioned in #11. Feel free to modify the script at your own whim.
